### ISSUE TITLE
Footer Link "Telegram Channel" points to wrong place

### ISSUE THREAD

**Issue by jollymike** [luminousmen/luminousmen.com#21]
Looking at the footer on [page](https://luminousmen.com/post/data-lake-vs-data-warehouse) I noticed the _License_ link and the _Telegram channel_ link  point to the same place.

        <footer>
    <a class='link' href='/about/'>About</a>
    <a class='link' href='/license/'>License</a>
    <a href="https://www.buymeacoffee.com/OheL3Mfnp" target="blank">Support author</a>
    <a class='link' href='/license/'>Telegram channel</a>
    <a class='link' href='/feeds/'>RSS</a>
    <a class='link' href='https://feedly.com/i/subscription/feed%2Fhttps%3A%2F%2Fluminousmen.com%2Ffeeds%2F' target='blank'>Feedly</a>
    <div class='footer__copyright'>© Copyright luminousmen.com All Rights Reserved</div>
</footer>

**Comment by luminousmen** [comment]
Wow, thanks man! 
Sorry for the delay, fixed
